In [1]:
import pandas as pd

In [271]:
# Import data
df = pd.read_excel('table_seating.xlsx')
print(df.shape)

(870, 17)

In [276]:
# Take only accepted
df1 = df[df.Status=='Accepted'].dropna().reset_index()
print(df1.shape)

(573, 18)

In [277]:
# Keep only necessary columns
df2 = df1[['Name', 'Gender','Function', 'KP_REGION_DESCR', 'Year']].copy()
print(df2.shape)
df2.head()

(573, 5)

                Name Gender    Function KP_REGION_DESCR  Year
0        Abas,Austin      M       Audit        Reg West  29.0
1        Adams,Diana      F  Enterprise        Reg West  16.0
2       Adams,Daniel      M  Enterprise         Calgary  31.0
3         Adams,Dave      M  Enterprise        Reg West  29.0
4  Adie-MacKay,Nancy      F       Audit             GVA  22.0

In [278]:
# Fix Gender Null values
#df2.loc[413,'Gender'] = 'M'
df2.Gender.value_counts(dropna=False)

M    430
F    143
Name: Gender, dtype: int64

In [279]:
def quartiles(x):
    q1 = df2.Year.quantile(.25)
    q2 = df2.Year.quantile(.50)
    q3 = df2.Year.quantile(.75)
    q4 = df2.Year.quantile(1)
    
    if x <= q1:
        return 'q1'
    elif x <= q2:
        return 'q2'
    elif x <= q3:
        return 'q3'
    else:
        return 'q4'
df2['year_quartile'] = df2.Year.apply(quartiles).copy()
df2.drop('Year', inplace=True, axis=1)

In [417]:
cols = ['Gender','Function','KP_REGION_DESCR','year_quartile']
dummies = pd.get_dummies(df2[cols])
df3 = pd.concat([df2,dummies], axis=1).drop(cols, axis=1).set_index('Name')
df3.shape

(573, 18)

In [554]:
df3

,Gender_F,Gender_M,Function_Advisory,Function_Audit,Function_BES,Function_Enterprise,Function_Global Resource Centre,Function_Tax,KP_REGION_DESCR_Calgary,KP_REGION_DESCR_GTA,KP_REGION_DESCR_GVA,KP_REGION_DESCR_Montreal,KP_REGION_DESCR_Reg East,KP_REGION_DESCR_Reg West,year_quartile_q1,year_quartile_q2,year_quartile_q3,year_quartile_q4,ones
Name,,,,,,,,,,,,,,,,,,,
"Abas,Austin",0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1
"Adams,Diana",1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,1
"Adams,Daniel",0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,1
"Adams,Dave",0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,1
"Adie-MacKay,Nancy",1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1
"Alderson,Anna",1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1
"Allwright,Rob",0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,1
"Alvarez,Carlos",0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1
"Anderson,Rhonda",1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,1
"Andrew,Christine",1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1
"Ang,Irene",1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1
"Anton,Jolene",1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,1
"Araki,Steven",0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,1
"Armstrong,Peter",0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1
"Ashby,Brent",0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,1
"Ashwin,Rob",0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,1
"Assanand,Nik",0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1
"Audette,Yvon",0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1
"Auger,Dennis",0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,1
"Ayoub,Grace",1,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1
"Baker,Heather",1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1
"Baqar,Zamin",0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,1
"Baratta,Michael",0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1
"Bardwell,Lee",0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1
"Barichello,Steve",0,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,1
"Barr,James",0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1
"Barron,James",0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1
"Barthel,Yvonne",1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,1
"Basahti,Ravine",0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,1
"Basden,Colleen",1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Weatherdon,Bruce",0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,1
"Webster,Gary",0,1,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1
"Welwood,Jeffrey",0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1
"Whitaker,Dorothy",1,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,1
"Whitley,Richard",0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,1
"Wiebe,Greg",0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,1
"Willis,Bruce",0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1
"Wilshaw,Ian",0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1
"Wilshaw,Philippa",1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1
"Wilson,Dan",0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1
"Wilson,Shaun",0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1
"Wilton,Garry",0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,1
"Wingrove,Brandi",1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1
"Wong,Jonathan",0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1
"Wong,Francis",0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,1
"Wong,Elaine",1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1
"Wood,Diane",1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1
"Woodward Amaral,Yael",0,1,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1
"Woolford,Penelope",1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,1
"Woolford,Paul",0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,1
"Wyper,Scott",0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,1
"Xilinas,Angelos",0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1
"Yep,Alexandra",1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,1
"Yip-Chuck,Patrick",0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1
"Yung,David",0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1
"Zabarylo,Pamela",1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,1
"Zacharuk,Ed",0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,1
"Zajko,Lisa",1,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,1
"Zizian,Yanic",0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1
"Zych,David",0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1

In [550]:
df3['ones'] = 1
df3.shape

(573, 19)

In [567]:
df2['KP_REGION_DESCR'].value_counts()

GTA         233
GVA          95
Reg East     79
Montreal     59
Calgary      55
Reg West     52
Name: KP_REGION_DESCR, dtype: int64

In [551]:
index = {key: val for key, val in list(zip(range(0,50),df3.columns))}
params = {0: 8, 2:5, 3:5, 8:1, 9:7, 10:3, 11:1, 12:1,18:10 }

n_tables = 30
m_params = 19

all_tables = np.zeros((n_tables,m_params))
all_tables[0].shape

(19,)

In [557]:
index

{0: 'Gender_F',
 1: 'Gender_M',
 2: 'Function_Advisory',
 3: 'Function_Audit',
 4: 'Function_BES',
 5: 'Function_Enterprise',
 6: 'Function_Global Resource Centre',
 7: 'Function_Tax',
 8: 'KP_REGION_DESCR_Calgary',
 9: 'KP_REGION_DESCR_GTA',
 10: 'KP_REGION_DESCR_GVA',
 11: 'KP_REGION_DESCR_Montreal',
 12: 'KP_REGION_DESCR_Reg East',
 13: 'KP_REGION_DESCR_Reg West',
 14: 'year_quartile_q1',
 15: 'year_quartile_q2',
 16: 'year_quartile_q3',
 17: 'year_quartile_q4',
 18: 'ones'}

In [560]:
for key, value in params.items():
    print("Index:",key, "Params:", value)

Index: 0 Params: 8
Index: 2 Params: 5
Index: 3 Params: 5
Index: 8 Params: 1
Index: 9 Params: 7
Index: 10 Params: 3
Index: 11 Params: 1
Index: 12 Params: 1
Index: 18 Params: 10

In [558]:
all_tables[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [552]:
first_table = 0
for index, row in df3.iterrows():
    i=0
    for idx, param in params.items():
        if table_i[first_table] >= param:
            i += 1
            break
        else
    i

SyntaxError: invalid syntax (<ipython-input-552-991f7e9b764a>, line 8)

In [512]:
all_tables[0] += df3.iloc[0,:]
all_tables
i=0
table_i = all_tables[i]
for idx, param in params.items():
    print(idx)
    if table_i[idx] >= param:
        i += 1
        break
i

0
2
3

1

In [592]:
import numpy.linalg as la
x = np.random.rand(10000,10000)
X = pd.DataFrame(x)

In [601]:
type(X.values)

numpy.ndarray

In [600]:
X.values()

TypeError: 'numpy.ndarray' object is not callable

In [589]:
from time import time
t0 = time()
x @ x.T
t1 = time()
print(t1-t0)

26.09201955795288

In [596]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
scale.fit_transform(X.to_)

array([[-0.95683256,  0.70405474, -0.15072982, ...,  1.50194848,
        -1.73140239,  0.68386472],
       [ 0.52010543,  0.91029235, -0.96626868, ...,  0.13841173,
        -1.27735525,  0.52698966],
       [-0.50214439,  0.74210206, -0.51926164, ..., -1.56925712,
         0.68258782, -1.66565285],
       ...,
       [-1.55707609,  1.34660093, -0.56718337, ..., -0.38012705,
        -1.34373895, -1.35443067],
       [-0.87346091,  0.70978743, -0.19797075, ..., -1.42676939,
         0.56181472,  0.09738859],
       [-0.69196821,  1.5931664 ,  1.50530546, ...,  0.56473571,
         0.08435494,  1.16733784]])

In [576]:
x @ x.T

array([[0.71228536, 0.54440456, 0.69228028, 1.05833091],
       [0.54440456, 1.18856575, 1.17367386, 1.53287707],
       [0.69228028, 1.17367386, 1.47471061, 1.81694654],
       [1.05833091, 1.53287707, 1.81694654, 2.56461701]])

In [553]:
all_tables

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]])

In [451]:
all_tables += df3.iloc[0,:]

ValueError: Length of passed values is 30, index implies 19

In [313]:


#sorted(table, key=lambda x: x[1]['F'], reverse=False)

In [242]:
df2.KP_REGION_DESCR.value_counts()

GTA         276
GVA         108
Reg East     88
Montreal     87
Calgary      67
Reg West     61
Name: KP_REGION_DESCR, dtype: int64

In [240]:
df2.shape[0]/30

22.933333333333334

In [245]:
df2['Attending as'].value_counts()

Partner              564
New Partner           55
Retiring Partner      16
Managing Director     15
Associate Partner      8
Other                  4
Name: Attending as, dtype: int64

In [205]:
df2.Year.quantile(1)

42.0

In [195]:
df2['year_binary'] = [0 if i < 18 else 1 for i in df2.Year]

C:\Users\mciniello\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [200]:
df2

,Name,Email Address,Gender,Attending as,Function,KP_REGION_DESCR,Year,year_binary
0,"Abas,Austin",aabas@kpmg.ca,M,Partner,Audit,Reg West,29.0,1
1,"Adams,Diana",dtadams@kpmg.ca,F,Partner,Enterprise,Reg West,16.0,0
5,"Adams,Daniel",dbadams@kpmg.ca,M,Partner,Enterprise,Calgary,31.0,1
6,"Adams,Dave",daveadams@kpmg.ca,M,Partner,Enterprise,Reg West,29.0,1
7,"Adie-MacKay,Nancy",nadie@kpmg.ca,F,Partner,Audit,GVA,22.0,1
8,"Ahamed,Jameel",jahamed@kpmg.ca,M,Partner,Advisory,GVA,3.0,0
9,"Alderson,Anna",amalderson@kpmg.ca,F,Partner,Audit,Calgary,35.0,1
10,"Allan,Janet",jlallanfcpa@gmail.com,F,Retiring Partner,Audit,Reg East,37.0,1
11,"Allard,Jean-François",jeanfrancoisallard@kpmg.ca,M,New Partner,Advisory,Montreal,12.0,0
13,"Allwright,Rob",rallwright@kpmg.ca,M,Associate Partner,Tax,GTA,20.0,1
14,"Alvarez,Carlos",carlosalvarez@kpmg.ca,M,Partner,Audit,Calgary,19.0,1
15,"Anderson,Rhonda",rhondaanderson@kpmg.ca,F,Partner,Tax,Reg West,27.0,1
16,"Andrew,Christine",clandrew@kpmg.ca,F,Managing Director,BES,GTA,7.0,0
17,"Ang,Irene",iang@kpmg.ca,F,Partner,Advisory,GTA,14.0,0
18,"Anton,Jolene",janton@kpmg.ca,F,Partner,Enterprise,Reg West,15.0,0
19,"Araki,Steven",snaraki@kpmg.ca,M,Partner,Tax,GVA,26.0,1
20,"Armstrong,Peter",pearmstrong@kpmg.ca,M,Partner,Advisory,GTA,27.0,1
21,"Ashby,Brent",bashby@kpmg.ca,M,Partner,Enterprise,Reg West,21.0,1
22,"Ashwin,Rob",robashwin@kpmg.ca,M,Partner,Tax,GVA,30.0,1
23,"Assanand,Nik",nassanand@kpmg.ca,M,Partner,Audit,GVA,22.0,1
25,"Atkins,Leontine",latkins@kpmg.ca,F,NaN,NaN,Calgary,25.0,1
26,"Audette,Yvon",yaudette@kpmg.ca,M,Partner,Advisory,GTA,15.0,0
27,"Auger,Dennis",dauger@kpmg.ca,M,Partner,Enterprise,Calgary,21.0,1
28,"Awasthi,Vaibhav",vawasthi@cvent.com,M,NaN,NaN,NaN,NaN,1
29,"Ayoub,Grace",gayoub@kpmg.ca,F,Partner,Advisory,Montreal,6.0,0
30,"Bain,John",jbain1@kpmg.ca,M,NaN,NaN,GTA,11.0,0
31,"Baker,Heather",hjbaker@kpmg.ca,F,Partner,Audit,GTA,35.0,1
32,"Baqar,Zamin",zbaqar@kpmg.ca,M,Partner,Enterprise,GTA,19.0,1
33,"Baratta,Michael",mbaratta@kpmg.ca,M,Partner,Audit,Montreal,22.0,1
34,"Bardwell,Lee",lbardwell@kpmg.ca,M,Partner,Audit,Calgary,20.0,1
...,...,...,...,...,...,...,...,...
829,"Whitley,Richard",rwhitley@kpmg.ca,M,Partner,Tax,Calgary,34.0,1
830,"Wiebe,Greg",gwiebe@kpmg.ca,M,Partner,Tax,GTA,34.0,1
831,"Willis,Bruce",brucewillis@kpmg.ca,M,Partner,Advisory,Reg West,17.0,0
832,"Wilshaw,Ian",idwilshaw@kpmg.ca,M,Partner,Advisory,GVA,15.0,0
833,"Wilshaw,Philippa",ppwilshaw@kpmg.ca,F,Partner,Audit,GVA,15.0,0
835,"Wilson,Jamie",jamiewilson1@kpmg.ca,M,Retiring Partner,Audit,Reg West,0.0,0
837,"Wilson,Dan",danwilson@kpmg.ca,M,Partner,Audit,GTA,20.0,1
838,"Wilson,Shaun",shwilson@kpmg.ca,M,Partner,Advisory,GVA,28.0,1
839,"Wilton,Garry",gwilton@kpmg.ca,M,Partner,Tax,Calgary,14.0,0
841,"Wingrove,Brandi",bwingrove@kpmg.ca,F,Partner,Audit,GVA,21.0,1
842,"Wise,Barbara",bdwise@kpmg.ca,F,Managing Director,NaN,GTA,24.0,1
843,"Wong,Jonathan",jonathanwong@kpmg.ca,M,New Partner,Audit,GVA,9.0,0
844,"Wong,Francis",fnwong@kpmg.ca,M,Partner,Enterprise,GVA,20.0,1
845,"Wong,Elaine",ewong6@kpmg.ca,F,Partner,Advisory,Calgary,18.0,1
847,"Wood,Diane",dianejwood@kpmg.ca,F,Partner,Tax,Reg East,34.0,1
848,"Woods,Erik",erikwoods@kpmg.ca,M,Partner,Advisory,GTA,1.0,0
851,"Woodward Amaral,Yael",ywoodward@kpmg.ca,M,Partner,Audit,GTA,12.0,0
852,"Woolford,Penelope",pennywoolford@kpmg.ca,F,Partner,Tax,GTA,30.0,1
854,"Woolford,Paul",paulwoolford@kpmg.ca,M,Partner,Enterprise,GTA,19.0,1
856,"Wyper,Scott",swyper@kpmg.ca,M,Partner,Tax,GVA,35.0,1
857,"Xilinas,Angelos",axilinas@kpmg.ca,M,Partner,Tax,GVA,19.0,1
858,"Yep,Alexandra",ayep@kpmg.ca,F,Partner,Tax,GTA,22.0,1
859,"Yip-Chuck,Patrick",pyipchuck@kpmg.ca,M,Partner,Advisory,GTA,33.0,1
860,"Yung,David",dyung@kpmg.ca,M,Partner,Audit,Calgary,13.0,0
861,"Zabarylo,Pamela",pzabarylo@kpmg.ca,F,Partner,Tax,GTA,25.0,1
862,"Zacharuk,Ed",ezacharuk@kpmg.ca,M,Partner,Tax,GVA,29.0,1
863,"Zajko,Lisa",lzajko@kpmg.ca,F,New Partner,Tax,GTA,0.0,0
864,"Zhu,Helen",helenzhu@kpmg.ca,F,Partner,Audit,GTA,6.0,0
865,"Zizian,Yanic",yzizian@kpmg.ca,M,Partner,Audit,Montreal,14.0,0
866,"Zych,David",dzych@kpmg.ca,M,Partner,Audit,Reg East,33.0,1

In [198]:
df2

,Name,Email Address,Gender,Attending as,Function,KP_REGION_DESCR,Year,year_bin,year_binary
0,"Abas,Austin",aabas@kpmg.ca,M,Partner,Audit,Reg West,29.0,1,1
1,"Adams,Diana",dtadams@kpmg.ca,F,Partner,Enterprise,Reg West,16.0,0,0
5,"Adams,Daniel",dbadams@kpmg.ca,M,Partner,Enterprise,Calgary,31.0,1,1
6,"Adams,Dave",daveadams@kpmg.ca,M,Partner,Enterprise,Reg West,29.0,1,1
7,"Adie-MacKay,Nancy",nadie@kpmg.ca,F,Partner,Audit,GVA,22.0,1,1
8,"Ahamed,Jameel",jahamed@kpmg.ca,M,Partner,Advisory,GVA,3.0,0,0
9,"Alderson,Anna",amalderson@kpmg.ca,F,Partner,Audit,Calgary,35.0,1,1
10,"Allan,Janet",jlallanfcpa@gmail.com,F,Retiring Partner,Audit,Reg East,37.0,1,1
11,"Allard,Jean-François",jeanfrancoisallard@kpmg.ca,M,New Partner,Advisory,Montreal,12.0,0,0
13,"Allwright,Rob",rallwright@kpmg.ca,M,Associate Partner,Tax,GTA,20.0,1,1
14,"Alvarez,Carlos",carlosalvarez@kpmg.ca,M,Partner,Audit,Calgary,19.0,1,1
15,"Anderson,Rhonda",rhondaanderson@kpmg.ca,F,Partner,Tax,Reg West,27.0,1,1
16,"Andrew,Christine",clandrew@kpmg.ca,F,Managing Director,BES,GTA,7.0,0,0
17,"Ang,Irene",iang@kpmg.ca,F,Partner,Advisory,GTA,14.0,0,0
18,"Anton,Jolene",janton@kpmg.ca,F,Partner,Enterprise,Reg West,15.0,0,0
19,"Araki,Steven",snaraki@kpmg.ca,M,Partner,Tax,GVA,26.0,1,1
20,"Armstrong,Peter",pearmstrong@kpmg.ca,M,Partner,Advisory,GTA,27.0,1,1
21,"Ashby,Brent",bashby@kpmg.ca,M,Partner,Enterprise,Reg West,21.0,1,1
22,"Ashwin,Rob",robashwin@kpmg.ca,M,Partner,Tax,GVA,30.0,1,1
23,"Assanand,Nik",nassanand@kpmg.ca,M,Partner,Audit,GVA,22.0,1,1
25,"Atkins,Leontine",latkins@kpmg.ca,F,NaN,NaN,Calgary,25.0,1,1
26,"Audette,Yvon",yaudette@kpmg.ca,M,Partner,Advisory,GTA,15.0,0,0
27,"Auger,Dennis",dauger@kpmg.ca,M,Partner,Enterprise,Calgary,21.0,1,1
28,"Awasthi,Vaibhav",vawasthi@cvent.com,M,NaN,NaN,NaN,NaN,1,1
29,"Ayoub,Grace",gayoub@kpmg.ca,F,Partner,Advisory,Montreal,6.0,0,0
30,"Bain,John",jbain1@kpmg.ca,M,NaN,NaN,GTA,11.0,0,0
31,"Baker,Heather",hjbaker@kpmg.ca,F,Partner,Audit,GTA,35.0,1,1
32,"Baqar,Zamin",zbaqar@kpmg.ca,M,Partner,Enterprise,GTA,19.0,1,1
33,"Baratta,Michael",mbaratta@kpmg.ca,M,Partner,Audit,Montreal,22.0,1,1
34,"Bardwell,Lee",lbardwell@kpmg.ca,M,Partner,Audit,Calgary,20.0,1,1
...,...,...,...,...,...,...,...,...,...
829,"Whitley,Richard",rwhitley@kpmg.ca,M,Partner,Tax,Calgary,34.0,1,1
830,"Wiebe,Greg",gwiebe@kpmg.ca,M,Partner,Tax,GTA,34.0,1,1
831,"Willis,Bruce",brucewillis@kpmg.ca,M,Partner,Advisory,Reg West,17.0,0,0
832,"Wilshaw,Ian",idwilshaw@kpmg.ca,M,Partner,Advisory,GVA,15.0,0,0
833,"Wilshaw,Philippa",ppwilshaw@kpmg.ca,F,Partner,Audit,GVA,15.0,0,0
835,"Wilson,Jamie",jamiewilson1@kpmg.ca,M,Retiring Partner,Audit,Reg West,0.0,0,0
837,"Wilson,Dan",danwilson@kpmg.ca,M,Partner,Audit,GTA,20.0,1,1
838,"Wilson,Shaun",shwilson@kpmg.ca,M,Partner,Advisory,GVA,28.0,1,1
839,"Wilton,Garry",gwilton@kpmg.ca,M,Partner,Tax,Calgary,14.0,0,0
841,"Wingrove,Brandi",bwingrove@kpmg.ca,F,Partner,Audit,GVA,21.0,1,1
842,"Wise,Barbara",bdwise@kpmg.ca,F,Managing Director,NaN,GTA,24.0,1,1
843,"Wong,Jonathan",jonathanwong@kpmg.ca,M,New Partner,Audit,GVA,9.0,0,0
844,"Wong,Francis",fnwong@kpmg.ca,M,Partner,Enterprise,GVA,20.0,1,1
845,"Wong,Elaine",ewong6@kpmg.ca,F,Partner,Advisory,Calgary,18.0,1,1
847,"Wood,Diane",dianejwood@kpmg.ca,F,Partner,Tax,Reg East,34.0,1,1
848,"Woods,Erik",erikwoods@kpmg.ca,M,Partner,Advisory,GTA,1.0,0,0
851,"Woodward Amaral,Yael",ywoodward@kpmg.ca,M,Partner,Audit,GTA,12.0,0,0
852,"Woolford,Penelope",pennywoolford@kpmg.ca,F,Partner,Tax,GTA,30.0,1,1
854,"Woolford,Paul",paulwoolford@kpmg.ca,M,Partner,Enterprise,GTA,19.0,1,1
856,"Wyper,Scott",swyper@kpmg.ca,M,Partner,Tax,GVA,35.0,1,1
857,"Xilinas,Angelos",axilinas@kpmg.ca,M,Partner,Tax,GVA,19.0,1,1
858,"Yep,Alexandra",ayep@kpmg.ca,F,Partner,Tax,GTA,22.0,1,1
859,"Yip-Chuck,Patrick",pyipchuck@kpmg.ca,M,Partner,Advisory,GTA,33.0,1,1
860,"Yung,David",dyung@kpmg.ca,M,Partner,Audit,Calgary,13.0,0,0
861,"Zabarylo,Pamela",pzabarylo@kpmg.ca,F,Partner,Tax,GTA,25.0,1,1
862,"Zacharuk,Ed",ezacharuk@kpmg.ca,M,Partner,Tax,GVA,29.0,1,1
863,"Zajko,Lisa",lzajko@kpmg.ca,F,New Partner,Tax,GTA,0.0,0,0
864,"Zhu,Helen",helenzhu@kpmg.ca,F,Partner,Audit,GTA,6.0,0,0
865,"Zizian,Yanic",yzizian@kpmg.ca,M,Partner,Audit,Montreal,14.0,0,0
866,"Zych,David",dzych@kpmg.ca,M,Partner,Audit,Reg East,33.0,1,1

In [185]:
df2['Attending as'].value_counts()

Partner              564
New Partner           55
Retiring Partner      16
Managing Director     15
Associate Partner      8
Other                  4
Name: Attending as, dtype: int64

In [187]:
table = {'F':0, }

21.0    42
13.0    29
20.0    29
18.0    28
19.0    26
22.0    24
0.0     23
12.0    23
23.0    22
17.0    22
1.0     22
24.0    21
7.0     20
3.0     20
28.0    19
14.0    19
6.0     18
15.0    18
4.0     18
27.0    18
34.0    17
16.0    16
29.0    16
33.0    16
11.0    14
26.0    14
2.0     13
31.0    12
8.0     12
10.0    11
25.0    11
9.0     10
5.0     10
35.0     9
30.0     9
37.0     8
32.0     8
36.0     7
38.0     7
40.0     3
41.0     2
42.0     1
Name: Year, dtype: int64

In [180]:
df1.Gender.value_counts(dropna=False)

M      509
F      178
NaN      1
Name: Gender, dtype: int64

,Name,Email Address,Gender,Attending as,Function,KP_REGION_DESCR,Year
413,"Lachance,Hugues",hlachance@kpmg.ca,NaN,Partner,Tax,Montreal,28.0

TypeError: '<' not supported between instances of 'float' and 'str'

In [134]:
x = {}
i=1
for a,b in split.split(df2.drop('Gender', axis=1), df2['Gender']):
    None

TypeError: '<' not supported between instances of 'float' and 'str'